# Generated by Django 5.1.6 on 2025-04-13 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_alter_customer_state_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('+1', 'United States'), ('+44', 'United Kingdom'), ('+1', 'Canada'), ('+61', 'Australia'), ('+91', 'India'), ('+49', 'Germany'), ('+33', 'France'), ('+86', 'China'), ('+81', 'Japan'), ('+82', 'South Korea'), ('+55', 'Brazil'), ('+27', 'South Africa'), ('+7', 'Russia'), ('+52', 'Mexico'), ('+39', 'Italy'), ('+34', 'Spain'), ('+31', 'Netherlands'), ('+65', 'Singapore'), ('+971', 'UAE'), ('+966', 'Saudi Arabia')], default='+91', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number with country code (e.g. +91-9876543210 or +919876543210)', regex='^\\+?\\d{1,3}[- ]?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('CR', 'Curd'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
